//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblegum.Service.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventmonitor
    {
        public System.Guid EventGUID { get; set; }
        public int ServerID { get; set; }
        public int Code { get; set; }
        public string Source { get; set; }
        public string Text { get; set; }
        public int Count { get; set; }
        public System.DateTime LastTimeStamp { get; set; }
    
        public virtual servers servers { get; set; }
    }
}
