//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finn.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diskmonitor
    {
        public System.Guid DiskGUID { get; set; }
        public int ServerID { get; set; }
        public string DiskLetter { get; set; }
        public string DiskLabel { get; set; }
        public int DiskSize { get; set; }
        public int DiskFree { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual servers servers { get; set; }
    }
}
