//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblegum.Service.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class hardwarehistory
    {
        public System.Guid HwMonGUID { get; set; }
        public int ServerID { get; set; }
        public int RAMFree { get; set; }
        public int CPULoad { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual servers servers { get; set; }
    }
}
