//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblegum.Service.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicemonitor
    {
        public System.Guid ServiceGUID { get; set; }
        public int ServerID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceDisplayName { get; set; }
        public string State { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual servers servers { get; set; }
    }
}
